### PR TITLE
Create .editorconfig

### PR DESCRIPTION
**Pull request by ntwb**

### CODE REVIEW

**Comment by karmatosed** [comment]
Why do we need this? It's just a theme and this adds something I am not sure we need.

**Comment by karmatosed** [comment]
Closing as we don't need this.

**Comment by ntwb** [comment]
I believe we should include it, it helps contributors Editor/IDE programs follow WPs coding standards and helps prevent the blank end-of-file line removed in https://github.com/WordPress/gutenberg-starter-theme/pull/33/commits/887d6d8eced19e07889adbe5fccae3338a3c6146

There was another example from another https://github.com/WordPress repo recently that currently alludes me where the addition of an `.editorconfig` file would have saved a heap of time for both the contributor and myself reviewing the PR

**Comment by karmatosed** [comment]
Awesome, merging thanks.

**Pull request merged**
