### PR TITLE
Add WordPress.org override styles

### PR DESCRIPTION
**Pull request by melchoyce**
Unsure if this should actually live in the theme or not, but I’ve added
it here for record-keeping at least.

### CODE REVIEW

**Comment by ntwb** [comment]
Is this deployed on w.org?

It could be wrapped in a `HTTP_HOST` check, something along the lines of:

```php
if ( false !== strpos($_SERVER['HTTP_HOST'], 'wordpress.org')) {
  wp_enqueue_style( 'gutenbergthemeblocks-style', get_template_directory_uri() . '/overrides.css');
}
```

**Comment by melchoyce** [comment]
Not deployed yet, no. Thanks for the suggestion! @obenland does that look good to swap into my PR ^ ?

**Comment by obenland** [comment]
We've been trying to base dotorg themes on a common parent theme that [handles those style overrides](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg/css/objects/_wporg-header.scss). For Gutenberg I had those styles compiled and [added to the regular stylesheet](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/gutenberg/style.css#L928). If you want I could just append those there?

**Comment by ntwb** [comment]
That sounds like the way to go @obenland 👍

**Comment by melchoyce** [comment]
Yeah sounds good, thanks @obenland 👍

**Comment by ntwb** [comment]
This was committed in https://meta.trac.wordpress.org/changeset/5822

**Pull request closed without merging**
